services:
  spool:
    image: $REGISTRY/spool:$VERSION
    tty: true
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        while true; do
          spool --dir /app/services --project spool
          sleep 30
        done
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/app/services
